# uncompyle6 version 2.9.10
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.0b2 (default, Oct 11 2016, 05:27:10) 
# [GCC 6.2.0 20161005]
# Embedded file name: kisu_errors.py
KS_ERROR_MAX_CRASH_COUNT = 4007985153
KS_USERCOMMS_ERROR_LIB_NOT_INITIALIZED = 4008050689
KS_USERCOMMS_ERROR_LIB_NATIVE_FUNCTIONS = 4008050690
KS_USERCOMMS_ERROR_OBJECTINFOVERSION_UNSUPPORTED = 4008050691
KS_USERCOMMS_ERROR_REMOTEV1_UNSUPPORTED = 4008050692
KS_USERCOMMS_ERROR_CACHE_UNSUPPORTED = 4008050693
KS_USERCOMMS_ERROR_LOCAL_V1_NOTLOADED = 4008050703
KS_USERCOMMS_ERROR_SIGNAL_V1_INVALID = 4008050704
KS_USERCOMMS_ERROR_SIGNAL_V1_INPROGRESS = 4008050705
KS_USERCOMMS_ERROR_SIGNAL_V1_ENVIRONMENTVAR = 4008050706
KS_USERCOMMS_ERROR_SIGNAL_V1_NOTACTIVE = 4008050707
KS_USERCOMMS_ERROR_SIGNAL_V1_CREATE_TIMER = 4008050708
KS_USERCOMMS_ERROR_SIGNAL_V1_START_TIMER = 4008050709
KS_USERCOMMS_ERROR_SIGNAL_V1_TIMER_FAILED = 4008050710
KS_USERCOMMS_ERROR_SIGNAL_V1_OPEN_PROCESS = 4008050711
KS_USERCOMMS_ERROR_SIGNAL_V1_PROCESSINFOGET = 4008050712
KS_USERCOMMS_ERROR_SIGNAL_V1_PROCESSINFOSET = 4008050713
KS_USERCOMMS_ERROR_SIGNAL_V1_TIMEOUT = 4008050714
KS_USERCOMMS_ERROR_SIGNAL_V1_CREATE_THREAD = 4008050715
KS_USERCOMMS_ERROR_SIGNAL_V2_INVALID = 4008050720
KS_USERCOMMS_ERROR_SIGNAL_V2_ENUMERATION = 4008050721
KS_USERCOMMS_ERROR_SIGNAL_V2_TIMEOUT = 4008050722
KS_USERCOMMS_ERROR_UNSUPPORTED = 4008050736
KS_USERCOMMS_ERROR_KS_NOT_INITIALIZED = 4008050737
KS_USERCOMMS_ERROR_KS_DEFAULT = 4008050738
KS_USERCOMMS_ERROR_KS_INVALID_PARAMETER = 4008050739
KS_USERCOMMS_ERROR_KS_INVALID_DATA = 4008050740
KS_USERCOMMS_ERROR_KS_NOT_ENOUGH_MEMORY = 4008050741
KS_USERCOMMS_ERROR_KS_EXCEPTION_THROWN = 4008050742
KS_USERCOMMS_ERROR_KS_INSUFFICIENT_BUFFER = 4008050743
KS_USERCOMMS_ERROR_KS_SERVICE_NOT_FOUND = 4008050744
KS_USERCOMMS_ERROR_KS_EVENT_ERROR = 4008050745
KS_USERCOMMS_ERROR_KS_INVALID_PE_FORMAT = 4008050746
KS_USERCOMMS_ERROR_KS_RELOCATTING_MODULE = 4008050747
KS_USERCOMMS_ERROR_KS_RESOLVE_IMPORTS = 4008050748
KS_USERCOMMS_ERROR_KS_OBFUSCATE_PE = 4008050749
KS_USERCOMMS_ERROR_KS_DLL_INIT_FAILED = 4008050750
KS_USERCOMMS_ERROR_KS_PROCEDURE_NOT_FOUND = 4008050751
KS_USERCOMMS_ERROR_KS_INVALID_IMPORT_OF_NON_DLL = 4008050752
KS_USERCOMMS_ERROR_KS_FIND_EXPORTED_FUNC = 4008050753
KS_USERCOMMS_ERROR_KS_REMOVE_MODULE = 4008050754
KS_USERCOMMS_ERROR_KS_MODULE_NOT_FOUND = 4008050755
KS_USERCOMMS_ERROR_KS_LOAD_SELF_EXCEPTION = 4008050756
KS_USERCOMMS_ERROR_KS_FAILED_CREATETHREAD = 4008050757
KS_USERCOMMS_ERROR_KS_UML_IMPORT_OF_ORDINAL = 4008050758
KS_USERCOMMS_ERROR_KS_LOADEDCOUNT_MUTEX = 4008050759
KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHUASTED = 4008050760
KS_USERCOMMS_ERROR_ASBT_WRAPPER_CREATION_FAILED = 4008050761
KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHAUSTED = 4008050762
KS_USERCOMMS_ERROR_KS_ALREADY_IN_PROCESS = 4008050763
KS_USERCOMMS_ERROR_KS_MODULE_TOO_LARGE = 4008050764
KS_USERCOMMS_ERROR_ASBT_VIRTUALALLOC_FAILED = 4008050765
KS_USERCOMMS_ERROR_ASBT_TLSALLOC_FAILED = 4008050766
KS_USERCOMMS_ERROR_KS_EXCEPTION_LOADING_DLL = 4008050767
KS_USERCOMMS_ERROR_KS_WRITE_FAILED = 4008050768
KS_USERCOMMS_ERROR_KS_READ_FAILED = 4008050769
KS_USERCOMMS_ERROR_INSTANCECACHE_INVALID = 4008050784
KS_USERCOMMS_ERROR_INSTANCECACHE_DELETED = 4008050785
KS_USERCOMMS_ERROR_INSTANCECACHE_UNKNOWN = 4008050786
KS_USERCOMMS_ERROR_INSTANCECACHE_ACQUIRE = 4008050787
KS_USERCOMMS_ERROR_INSTANCECACHE_RELEASE = 4008050788
KS_USERCOMMS_ERROR_INSTANCECACHE_CREATE = 4008050789
KS_USERCOMMS_ERROR_INSTANCECACHE_MARKDESTROY = 4008050790
KS_USERCOMMS_ERROR_INSTANCECACHE_ADD = 4008050791
KS_USERCOMMS_ERROR_INSTANCECACHE_REMOVE = 4008050792
KS_USERCOMMS_ERROR_INSTANCECACHE_ENTRY_ALREADY_EXISTS = 4008050793
KS_USERCOMMS_ERROR_INSTANCECACHE_ENTRY_NOT_FOUND = 4008050794
KS_USERCOMMS_ERROR_INSTANCECACHE_SYNC = 4008050795
KS_USERCOMMS_ERROR_INSTANCEENTRY_INVALID = 4008050800
KS_USERCOMMS_ERROR_INSTANCEENTRY_DELETED = 4008050801
KS_USERCOMMS_ERROR_INSTANCEENTRY_UNKNOWN = 4008050802
KS_USERCOMMS_ERROR_INSTANCEENTRY_ACQUIRE = 4008050803
KS_USERCOMMS_ERROR_INSTANCEENTRY_RELEASE = 4008050804
KS_USERCOMMS_ERROR_INSTANCEENTRY_CREATE = 4008050805
KS_USERCOMMS_ERROR_INSTANCEENTRY_MARKDESTROY = 4008050806
KS_USERCOMMS_ERROR_INSTANCE_INVALID = 4008050816
KS_USERCOMMS_ERROR_INSTANCE_NOTFOUND = 4008050817
KS_USERCOMMS_ERROR_INSTANCECACHE_NOTFOUND = 4008050818
errorStrings = {KS_ERROR_MAX_CRASH_COUNT: 'Max crash count reached',
   KS_USERCOMMS_ERROR_LIB_NOT_INITIALIZED: 'Library is not initialized or is shutting down',
   KS_USERCOMMS_ERROR_LIB_NATIVE_FUNCTIONS: 'Missing required native function',
   KS_USERCOMMS_ERROR_OBJECTINFOVERSION_UNSUPPORTED: 'The objectInfoVersion requested is unsupported with this KISU instance',
   KS_USERCOMMS_ERROR_REMOTEV1_UNSUPPORTED: 'Operations using Remote Version 1 signaling unsupported',
   KS_USERCOMMS_ERROR_CACHE_UNSUPPORTED: 'Operations using the instance cache are unsupported',
   KS_USERCOMMS_ERROR_LOCAL_V1_NOTLOADED: 'Local KISU instance not loaded',
   KS_USERCOMMS_ERROR_SIGNAL_V1_INVALID: 'Signaling to Version 1.x obtained invalid data from the callback',
   KS_USERCOMMS_ERROR_SIGNAL_V1_INPROGRESS: 'Signaling to Version 1.x already in progress by another library',
   KS_USERCOMMS_ERROR_SIGNAL_V1_ENVIRONMENTVAR: 'Environment variable setup failed during signaling to Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_NOTACTIVE: 'Data for signaling to Version 1.x not active',
   KS_USERCOMMS_ERROR_SIGNAL_V1_CREATE_TIMER: 'Unable to create timer for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_START_TIMER: 'Unable to start timer for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_TIMER_FAILED: 'Failed to wait on timer for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_OPEN_PROCESS: 'Unable to open process for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_PROCESSINFOGET: 'Unable to get process information for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_PROCESSINFOSET: 'Unable to set process information for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_TIMEOUT: 'Timed out waiting for a version 1.x callback',
   KS_USERCOMMS_ERROR_SIGNAL_V1_CREATE_THREAD: 'Failed to create a thread for version 1.x signaling',
   KS_USERCOMMS_ERROR_SIGNAL_V2_INVALID: 'Signaling to Version 2.x obtained invalid data',
   KS_USERCOMMS_ERROR_SIGNAL_V2_ENUMERATION: 'Signaling to Version 2.x failed to enumerate list',
   KS_USERCOMMS_ERROR_SIGNAL_V2_TIMEOUT: 'Timed out waiting for a version 2.x callback',
   KS_USERCOMMS_ERROR_UNSUPPORTED: 'Call is unsupported in requested killsuit instance',
   KS_USERCOMMS_ERROR_KS_NOT_INITIALIZED: 'Killsuit instance provided is not initialized',
   KS_USERCOMMS_ERROR_KS_DEFAULT: 'KS_USERCOMMS_ERROR_KS_DEFAULT',
   KS_USERCOMMS_ERROR_KS_INVALID_PARAMETER: 'KS_USERCOMMS_ERROR_KS_INVALID_PARAMETER',
   KS_USERCOMMS_ERROR_KS_INVALID_DATA: 'KS_USERCOMMS_ERROR_KS_INVALID_DATA',
   KS_USERCOMMS_ERROR_KS_NOT_ENOUGH_MEMORY: 'KS_USERCOMMS_ERROR_KS_NOT_ENOUGH_MEMORY',
   KS_USERCOMMS_ERROR_KS_EXCEPTION_THROWN: 'KS_USERCOMMS_ERROR_KS_EXCEPTION_THROWN',
   KS_USERCOMMS_ERROR_KS_INSUFFICIENT_BUFFER: 'KS_USERCOMMS_ERROR_KS_INSUFFICIENT_BUFFER',
   KS_USERCOMMS_ERROR_KS_SERVICE_NOT_FOUND: 'KS_USERCOMMS_ERROR_KS_SERVICE_NOT_FOUND',
   KS_USERCOMMS_ERROR_KS_EVENT_ERROR: 'KS_USERCOMMS_ERROR_KS_EVENT_ERROR',
   KS_USERCOMMS_ERROR_KS_INVALID_PE_FORMAT: 'KS_USERCOMMS_ERROR_KS_INVALID_PE_FORMAT',
   KS_USERCOMMS_ERROR_KS_RELOCATTING_MODULE: 'KS_USERCOMMS_ERROR_KS_RELOCATTING_MODULE',
   KS_USERCOMMS_ERROR_KS_RESOLVE_IMPORTS: 'KS_USERCOMMS_ERROR_KS_RESOLVE_IMPORTS',
   KS_USERCOMMS_ERROR_KS_OBFUSCATE_PE: 'KS_USERCOMMS_ERROR_KS_OBFUSCATE_PE',
   KS_USERCOMMS_ERROR_KS_DLL_INIT_FAILED: 'KS_USERCOMMS_ERROR_KS_DLL_INIT_FAILED',
   KS_USERCOMMS_ERROR_KS_PROCEDURE_NOT_FOUND: 'KS_USERCOMMS_ERROR_KS_PROCEDURE_NOT_FOUND',
   KS_USERCOMMS_ERROR_KS_INVALID_IMPORT_OF_NON_DLL: 'KS_USERCOMMS_ERROR_KS_INVALID_IMPORT_OF_NON_DLL',
   KS_USERCOMMS_ERROR_KS_FIND_EXPORTED_FUNC: 'KS_USERCOMMS_ERROR_KS_FIND_EXPORTED_FUNC',
   KS_USERCOMMS_ERROR_KS_REMOVE_MODULE: 'KS_USERCOMMS_ERROR_KS_REMOVE_MODULE',
   KS_USERCOMMS_ERROR_KS_MODULE_NOT_FOUND: 'KS_USERCOMMS_ERROR_KS_MODULE_NOT_FOUND',
   KS_USERCOMMS_ERROR_KS_LOAD_SELF_EXCEPTION: 'KS_USERCOMMS_ERROR_KS_LOAD_SELF_EXCEPTION',
   KS_USERCOMMS_ERROR_KS_FAILED_CREATETHREAD: 'KS_USERCOMMS_ERROR_KS_FAILED_CREATETHREAD',
   KS_USERCOMMS_ERROR_KS_UML_IMPORT_OF_ORDINAL: 'KS_USERCOMMS_ERROR_KS_UML_IMPORT_OF_ORDINAL',
   KS_USERCOMMS_ERROR_KS_LOADEDCOUNT_MUTEX: 'KS_USERCOMMS_ERROR_KS_LOADEDCOUNT_MUTEX',
   KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHUASTED: 'KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHUASTED',
   KS_USERCOMMS_ERROR_ASBT_WRAPPER_CREATION_FAILED: 'KS_USERCOMMS_ERROR_ASBT_WRAPPER_CREATION_FAILED',
   KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHAUSTED: 'KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHAUSTED',
   KS_USERCOMMS_ERROR_KS_ALREADY_IN_PROCESS: 'KS_USERCOMMS_ERROR_KS_ALREADY_IN_PROCESS',
   KS_USERCOMMS_ERROR_KS_MODULE_TOO_LARGE: 'KS_USERCOMMS_ERROR_KS_MODULE_TOO_LARGE',
   KS_USERCOMMS_ERROR_ASBT_VIRTUALALLOC_FAILED: 'KS_USERCOMMS_ERROR_ASBT_VIRTUALALLOC_FAILED',
   KS_USERCOMMS_ERROR_ASBT_TLSALLOC_FAILED: 'KS_USERCOMMS_ERROR_ASBT_TLSALLOC_FAILED',
   KS_USERCOMMS_ERROR_KS_EXCEPTION_LOADING_DLL: 'KS_USERCOMMS_ERROR_KS_EXCEPTION_LOADING_DLL',
   KS_USERCOMMS_ERROR_KS_WRITE_FAILED: 'KS_USERCOMMS_ERROR_KS_WRITE_FAILED',
   KS_USERCOMMS_ERROR_KS_READ_FAILED: 'KS_USERCOMMS_ERROR_KS_READ_FAILED',
   KS_USERCOMMS_ERROR_INSTANCECACHE_INVALID: 'Instance cache is invalid',
   KS_USERCOMMS_ERROR_INSTANCECACHE_DELETED: 'Instance cache is marked for deletion',
   KS_USERCOMMS_ERROR_INSTANCECACHE_UNKNOWN: 'Instance cache is an unknown version',
   KS_USERCOMMS_ERROR_INSTANCECACHE_ACQUIRE: 'Failed to acquire reference to instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_RELEASE: 'Failed to release reference to instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_CREATE: 'Failed to create instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_MARKDESTROY: 'Failed to mark instance cache for destruction',
   KS_USERCOMMS_ERROR_INSTANCECACHE_ADD: 'Failed to add to the instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_REMOVE: 'Failed to remove from the instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_ENTRY_ALREADY_EXISTS: 'Entry already existing in the specified cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_ENTRY_NOT_FOUND: 'Entry not found in the specified cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_SYNC: 'Failed to acquire synchronization object of cache',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_INVALID: 'Instance entry is invalid',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_DELETED: 'Instance entry is marked for deletion',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_UNKNOWN: 'Instance entry is an unknown version',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_ACQUIRE: 'Failed to acquire reference to instance entry',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_RELEASE: 'Failed to release reference to instance entry',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_CREATE: 'Failed to create instance entry',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_MARKDESTROY: 'Failed to mark instance entry for destruction',
   KS_USERCOMMS_ERROR_INSTANCE_INVALID: 'The given instance is invalid',
   KS_USERCOMMS_ERROR_INSTANCE_NOTFOUND: 'Instance not found',
   KS_USERCOMMS_ERROR_INSTANCECACHE_NOTFOUND: 'Instance cache not found'
   }